name: flutter_video_app
description: A Video app project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.4.3+2
  font_awesome_flutter: ^8.4.0
  path_provider: ^0.4.1
  permission_handler: ^3.0.0
  video_player: ^0.10.0+5
  simple_share: ^0.0.1+4
  thumbnails: ^1.0.1
  bloc_provider: ^0.5.0+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true